### ISSUE TITLE
Not working on Latest Version

### ISSUE THREAD

**Issue by AnKingMed** [kelciour/google-translate#10]
This is a fantastic add-on (very impressed). It looks like the editor toolbar was changed up in the latest version. Do you have time to update this to work with that? If not, I'm happy to pay another software engineer to look into it

**Comment by kelciour** [comment]
Thank you! The code is old but it seems to work fine for me on 2.1.46, a toolbar button is visible and clickable, and I'm not sure where could be the problem. In any way, I have no time at the moment and can only maybe do something maybe a week or two later.

![изображение](https://user-images.githubusercontent.com/16260735/128758333-94f9d292-f3ee-48eb-b9ce-e2ae2676ee5d.png)

**Comment by AnKingMed** [comment]
Ah you're right. Seems I had another conflict.  Thanks for checking so quick. Truly this is an awesome add-on!
