### ISSUE TITLE
Feature Request - romanization for 

### ISSUE THREAD

**Issue by AnKingMed** [kelciour/google-translate#12]
At the moment, the romanization is only added from the input side. I think it would be very helpful to add the romanization from the output side.  This would be useful for anyone studying an asian language from a latin-based language, otherwise you have to type the asian langauge in the input and translate backwards.

Example
![image](https://user-images.githubusercontent.com/57678116/129937559-b6bd3bb2-c208-4cc8-8694-c04e3ed7a114.png)

**Comment by kelciour** [comment]
Thank you for the feature request! The add-on was updated and I'll close the issue.

**Comment by AnKingMed** [comment]
Fantastic! Thank you!

**Comment by AnKingMed** [comment]
How is this supposed to be used? I see it in the Config, but not in the dialog box that is triggered from the edit screen. Even if I put "Extra" in the "target romanization" it doesn't work.

I also noticed if you do "examples" it gives you examples of the source word, not target.

Perhaps this is just me, but when making cards I typically make the word in English and then translate to the language I want to learn and ideally I want the romanization, examples, definition, etc of the target word (i.e. I don't need to see how an English word is used in English, but it is helpful to see how a Chinese word is used in Chinese because that's the language I'm trying to learn).  Hopefully that makes sense.   Perhaps it would be simplest just to have an extra toggle on the "Extras" (romanization, definition, example) that could allow the user to use the source or target to fill those fields?

**Comment by kelciour** [comment]
I'm sorry, it probably produced no results because the target field wasn't mapped to any field. The addon was updated and the "target romanization" or any other extra fields should work now even if the "target field" wasn't selected.

About extra fields ("definition", "example") using the target word as input, it could be done by making the second request to https://translate.google.com, but I'm afraid, I'll need some example when it works or makes sense. I tried to translate some word on https://translate.google.com and then used ⇄ to switch the translation and maybe get some definitions or examples, but it didn't go well.

**Comment by AnKingMed** [comment]
That's unfortunate.  I have been using the word "test" with English to Chinese and it seems to have info for all the options.  The target romanization works much better now. I think example would be nice for "test" in Chinese, but if it's not doable it's not the worst. Having target romanization is already a big step

**Comment by kelciour** [comment]
Your explanation makes a lot of sense and this option might be useful. I added it as a new branch at the moment and it could be installed by downloading .ankiaddon from Assets but I'm not sure if it'll work as expected all the time. I only tested it by translating "start" from English to Spanish.

https://github.com/kelciour/google-translate/releases/tag/v0.1-target-defs-and-exa

![изображение](https://user-images.githubusercontent.com/16260735/131200831-020d1409-6404-4e03-8961-1cf775ff9769.png)

**Comment by kelciour** [comment]
If it makes easier to install, it's now live on AnkiWeb, but hidden by default in the config file: 
`"Show Extra Options": false`

**Comment by AnKingMed** [comment]
Seems to work very well! I hate to suggest more because you've already been so helpful, but this would probably be my last suggestion.

My thought is you want:
Field 1: English word (assuming the studier already knows english)
Field 2: Chinese (or other) Translation
Field 3: Chinese (target) romanization
Field 4: Definition (probably would want this in English if I'm just beginning to learn Chinese)
Field 5: Alternative translations
Field 6: Examples in Chinese

Does that make sense as to why?  I didn't realize it till you got all this working, but I think definitions make more sense in the users source language, but examples make more sense in the target language.  I suppose having an option for everything is probably best, but this is how I imagine most people would personally study a language. 

Regardless, the reason I have been testing this so much is because I want to create a note type to fit with this add-on and then share it with everyone on r/Anki and publicize your work!

**Comment by kelciour** [comment]
It was added to the latest version.

There's no need to modify Config anymore to show extra options, they're visible by default now and could be toggle on/off from the context menu. If they're hidden, the add-on will ignore these options.

![mkU1BF3Zxq](https://user-images.githubusercontent.com/16260735/132996395-3f6a039a-34e7-4166-8357-cd9754a63d96.png)

In this case the translated results will be fetched twice (or thrice if to get alternative translations) with no timeout in between and there's a higher chance of getting "429 Client Error: Too Many Requests" from Google that will make Google Translate and the add-on stop working for some time, maybe half an hour or a few hours. If it happens, maybe it'd be better to add some sleeping between requests or maybe do something else.

Regarding sharing on r/Anki, that'd be great!

**Comment by AnKingMed** [comment]
This is super amazing! I love it! Goal is to create a note type that works very simply with this. Thanks for the updates!
