### ISSUE TITLE
Alternative translations

### ISSUE THREAD

**Issue by ghost** [kelciour/google-translate#13]
Hi!
Wondering if it's possible to make the meaning of the translated alternative definition not show up in the translated language (french in this case), instead just show altearnative words for the Expression field?
![image](https://user-images.githubusercontent.com/30667087/131224932-c6924ad3-6e0b-41c2-9152-314124c8eab0.png)
![image](https://user-images.githubusercontent.com/30667087/131224938-d682bc19-c112-4007-b9d7-6388c2e913c1.png)

**Comment by kelciour** [comment]
Do you mean like this?

![изображение](https://user-images.githubusercontent.com/16260735/132151645-2ffa771c-5640-450c-bee9-ae8c54565760.png)

**Comment by ghost** [comment]
Yep! That was what I thought. Because when you learn a language monolingually and look at the alternative words and see the translations into another language it's kind of against the whole point. Your screenshot would solve this perfectly :)

**Comment by kelciour** [comment]
The add-on was updated. The visibility can be changed with the context menu from "show" to "hide" (but keep HTML) or "remove".

![mkU1BF3Zxq](https://user-images.githubusercontent.com/16260735/132995347-dc82ac01-09f2-4b5d-85af-e5838fcf2fe5.png)
