### ISSUE TITLE
On-the-fly generation like Awesometts?

### ISSUE THREAD

**Issue by ghost** [kelciour/google-translate#14]
Would be cool if one could make on the fly definition generation. Especially useful for people like me who've got a lot of notes in a deck and use morphman to order their new cards, so the new ones constantly shift and most of the time bulk generating definitions is useless because of this and generating 10-20k card definitions if obviously impossible due to server restrictions. One would see a new card and it would fetch the definition or any fields specified in the addon automatically.
Anyways, don't know if this is something only I'm interested in or if someone else thought about it. Dunno if it's hard to implement either :)

**Comment by kelciour** [comment]
That's a great suggestion!

Some experimental basic support was added to the latest version but I don't know if it'll be usable or not. There will be a slight delay (up to a few seconds) before a new card is shown (to get translated results) and once Google says "429 Client Error: Too Many Requests", Google Translate and this feature will stop working until Anki is restarted and after waiting for some time, maybe half an hour or a few hours.

To enable it, edit the card template and add a special prefix to the field in curly brackets, e.g. `{{google-translate md auto,fr Word:Definitions}}` to get definitions (`md`) by translating the Word field from `auto` to French (`fr`) and save them in the Definitions field if it's empty, or `{{google-translate md auto,fr,text,write Word:Definitions}}` to get the translated results and overwrite the Definitions field if it's not empty.

The filter doesn't work in the card template, it will be shown as is if it's correct or some error message will be shown if its syntax isn't correct.

```
usage:

-- get a list of language codes
{{google-translate voices:}}

-- filter syntax
{{google-translate <data_type> <source_language>,<target_language>[,<format>,<if_not_empty>] <source_field>:<target_field>}}
-- <data_type> = t, rm, rmt, md, ex (t - translation, rm - romanization, rmt - romanization translated, md - definitions, ex - examples)
-- <format> = text (html is not implemented)
-- <if_not_empty> = s, skip, w, write (s = skip, w = write)

-- full syntax
{{google-translate t auto,en,text,s Example:Translation}}
{{google-translate t auto,en,text,w Example:Translation}}

-- short syntax
{{google-translate t auto,en Example:Translation}}
-- auto,en = auto,en,text,s

-- examples
{{google-translate t … Example:Translation}}
{{google-translate rm … Word:Romanization}}
{{google-translate rmt … Word:Romanization Target}}
{{google-translate md … Word:Definitions}}
{{google-translate ex … Word:Examples}}
```

**Comment by kelciour** [comment]
Alternatively, a combination of [Edit Field During Review](https://ankiweb.net/shared/info/1020366288) and [Additional Card Fields](https://ankiweb.net/shared/info/744725736) with a bit of JavaScript code could be used to fetch some definitions by translating {{Word}} from `en` to `fr` during review, if the Definition field was empty, and save it.

```html
<div id="definition" style="text-align: left;">{{Definition}}</div>

{{^Definition}}
<script>
fetch('https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=fr&dt=t&dt=rm&dt=md&dt=ex&q={{text:Word}}')
  .then(response => response.json())
  .then(data => {
    let definition = [];
    let langcode = "";
    try {
        langcode = data[2];
    } catch (e) { console.error(e) };
    try {
        for (let d of data[12]) {
            let part_of_speech = d[0];
            definition.push(`<div class="eIKIse" style="color: #1a73e8; font-weight: bold;">${part_of_speech}</div>`);
            definition.push('<ol>');
            for (let m of d[1]) {
                let defn = m[0];
                try {
                    let ex = "";
                    try {
                        ex = m[2]
                    } catch (e) { console.error(e) };
                    if (ex) {
                        if (langcode == 'ja') {
                            ex = ex.replace(/^「(.+)」$/, ' $1 ', ex);
                        }
                        defn += '<div class="MZgjEb" style="color: #5f6368; font-size: 19px;"';
                        if (langcode) {
                            defn += ` lang="${langcode}"`;
                        }
                        defn += `><q>${ex}</q></div>`;
                    }
                } catch (e) { console.error(e) };
                definition.push(`<li class="fw3eif">${defn}</li>`);
            }
            definition.push('</ol>')
        }
    } catch (e) { console.error(e) };
    definition = definition.join('');
    if (definition) {
        $('#definition').html(definition);
        if (pycmd !== undefined) {
            pycmd("ankisave#" + 'Definition' + "#" + {{info-Nid:}} + "#" + definition);
        }
    }
  })
  .catch(console.error);
</script>
{{/Definition}}
```
