### ISSUE TITLE
Loading fails in Ubuntu 21.10

### ISSUE THREAD

**Issue by rajaguha** [kelciour/google-translate#20]
When trying to add 'Google Translate' add-on on Ubuntu 21.10 with Anki 2.1.15 installed from Ubuntu repository, I get the following error:

> When loading 'Google Translate':
> Traceback (most recent call last):
>   File "/usr/share/anki/aqt/addons.py", line 80, in loadAddons
>     __import__(dir)
>   File "/home/rajag/.local/share/Anki2/addons21/1536291224/__init__.py", line 16, in <module>
>     from anki.template import TemplateRenderContext
> ImportError: cannot import name 'TemplateRenderContext' from 'anki.template' (/usr/share/anki/anki/template/__init__.py)

usr/share/anki/anki/template/__init__.py has the following 7 lines only:
```
from anki.template.template import Template
from anki.template.view import View

def render(template, context=None, **kwargs):
    context = context and context.copy() or {}
    context.update(kwargs)
    return Template(template, context).render()
```

**Comment by kelciour** [comment]
Anki 2.1.15 is too old - https://docs.ankiweb.net/platform/linux/distro-packages.html
The issue will disappear after installing Anki 2.1.49 from https://apps.ankiweb.net/#linux
