### ISSUE TITLE
Line 80 error, cannot use add-on with Anki 2.1.15

### ISSUE THREAD

**Issue by gregjswenson** [kelciour/google-translate#28]
![image](https://user-images.githubusercontent.com/57815571/201437626-a1666e83-60a7-4957-8ebd-bf2945cd20cf.png)

This is the error I receive. I need to stay on this version of Anki for some other add-ons to continue working. Any help appreciated with resolving this, thanks!

**Comment by kelciour** [comment]
Maybe try the version before this line was added. It should be https://github.com/kelciour/google-translate/tree/dc2bc02d875e1fffd2dac30dc9e4069f975425b6

**Comment by gregjswenson** [comment]
> Maybe try the version before this line was added. It should be https://github.com/kelciour/google-translate/tree/dc2bc02d875e1fffd2dac30dc9e4069f975425b6

Thank you for the suggestion. I tried using the files from the link you provided to make an add-on. This is the first time I've done this, so I tried replacing the current version of the add-on files with the older files. This resulted in an error upon restarting Anki.

Then I tried deleting all the files from the current add-on and only putting the add-on files from the link you provided into that folder. Restarting Anki again results in an error:

![image](https://user-images.githubusercontent.com/57815571/201478622-3c3131fc-f703-40e3-989a-44616bf90b0f.png)

**Comment by kelciour** [comment]
This error can be fixed by using `pyuic5 form.ui -o form.py` to autogenerate form.py but I just tested and there will be another error. Try this one instead - https://github.com/kelciour/google-translate/tree/60a2521a0138b9708556ac12d547041dac0ea173 and also add the attached form.py after unzipping it to fix `ImportError: cannot import name 'form'`.

[form.zip](https://github.com/kelciour/google-translate/files/9995203/form.zip)

**Comment by kelciour** [comment]
I uploaded this version on AnkiWeb for Anki 2.1.15. Try to reinstall the add-on.

**Comment by gregjswenson** [comment]
Install from AnkiWeb works! Thanks so much for fixing this! Sent you a coffee 😊
I would love one additional feature, if you can make time to add it: Stripping out the Cloze deletion syntax {{c1::}} before putting the field through Google Translate. All of my new cards are always Cloze deletion, but I find it distracting to have the Cloze syntax in the meaning field. I can strip it out manually, but I think others would also benefit from this feature (I saw mention of it in the user comments as well). Thanks for all your work!!

**Comment by kelciour** [comment]
That's great! Thank you! Thank you very much!

Please update the add-on again. The cloze deletions should be stripped now.

**Comment by gregjswenson** [comment]
You're welcome, and thank YOU for stripping out the Cloze deletion text!! This helps so much. Actually some of the translations were inaccurate for me before because I sometimes Cloze delete part of a word, and this was messing with the translation. But now with the Cloze deletion syntax stripped out it translates perfectly! I gave you a good review on the add-on page. I know others will benefit from your contribution to the Anki community. Best
