### ISSUE TITLE
Not working in anki 23.10

### ISSUE THREAD

**Issue by orangelover12** [kelciour/google-translate#34]
Hello!
First of all, I really like this add-on and I would like to thank you.
My issue is that ANKI 23.10 version came out today and this addon does not work.
I would really appreciate it if you could update it.
Have a good day!

**Comment by kelciour** [comment]
Is there any error message or something? The add-on seems to work for me, but if it's related to some changes by Google, it might take some time for me to experience it too.

**Comment by kelciour** [comment]
Ah, sorry, I forgot that I set ENABLE_QT5_COMPAT to 1 in the past. I'll try to update the add-on over the weekend.

In the meanwhile, adding a new environment variable ENABLE_QT5_COMPAT and setting it to 1, should make the add-on work for now.

https://forums.ankiweb.net/t/porting-tips-for-anki-23-10/35916#:~:text=ENABLE_QT5_COMPAT%20to%201

**Comment by kelciour** [comment]
Thank you for the report! The add-on was updated on AnkiWeb to support 23.10! If you didn't receive a notification by Anki, please run Tools > Add-ons > Check for Updates to update the add-on and restart Anki!
