### ISSUE TITLE
Error when trying to translate cards

### ISSUE THREAD

**Issue by danielswater** [kelciour/google-translate#37]
When I try to translate from English to Portuguese, it gives the following error:

Error:

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'english translation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\danie\AppData\Roaming\Anki2\addons21\1536291224\__init__.py", line 412, in accept
    for num, chunk in enumerate(self.chunkify(), 1):
  File "C:\Users\danie\AppData\Roaming\Anki2\addons21\1536291224\__init__.py", line 316, in chunkify
    if self.config["Overwrite"] or note[fld] == "":
  File "anki.notes", line 159, in __getitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'english translation'

![image](https://github.com/kelciour/google-translate/assets/20691771/83c0dd6e-e33b-468b-a1b8-e269b161b0a5)
![image](https://github.com/kelciour/google-translate/assets/20691771/1bb1750c-7fb3-469d-9c32-f5a68e17044e)

Os campos estão corretos:

![image](https://github.com/kelciour/google-translate/assets/20691771/d5bfe67e-f72b-4111-ab64-36f918df1863)

**Comment by kelciour** [comment]
I guess, you're trying to translate a few different note types at the same time and one of the note types doesn't contain the "english translation" field. I'll try to fix it some time later by skipping such notes.

In the meantime, maybe use the following search to find notes with the "english translation" field and translate only them.

```
"english translation:*"
```

**Comment by danielswater** [comment]
I tried to do this. No erros occurs, but nothing is translate

**Comment by kelciour** [comment]
Maybe try to use the add-on with a single note and double-check that the Source Field and Target Field are set correctly.

![image](https://github.com/kelciour/google-translate/assets/16260735/dace9175-8212-4c8c-8d4f-1eeb1f75df56)
