### ISSUE TITLE
Bug in Thai language

### ISSUE THREAD

**Issue by bansaito** [kelciour/google-translate#38]
There was a bug when translating Thai language.  When I tried to translate many cards.  There are no problems with other languages. please fix, I wasted hours translating it myself. 😥😥
![image](https://github.com/kelciour/google-translate/assets/168981876/4c470b81-3a4d-47ae-aa2b-8905f641534a)
![image](https://github.com/kelciour/google-translate/assets/168981876/96195d44-fdff-4670-a6d6-6fc366b71c7c)
![image](https://github.com/kelciour/google-translate/assets/168981876/e98a33c7-9e7a-4a0e-9360-14398680c1ea)

**Comment by kelciour** [comment]
I'm sorry but I can't help to translate this particular deck.

If the issue can be reproduced with any other deck, for example, [4000 Essential English Words (2nd Edition)](https://ankiweb.net/shared/info/1614672958), please create a new issue and I'll look into it.

**Comment by kelciour** [comment]
I had a hard time understanding the issue by looking at the screenshots, but I understand it now and was able to reproduce it on https://translate.google.com/

I'll try to fix it and update the add-on in the next few days.
