### ISSUE TITLE
Japanese Romanization in Batch Edit mode is broken

### ISSUE THREAD

**Issue by cnra** [kelciour/google-translate#42]
Hi,

Batch edit romanization was working a few weeks ago, but now Batch Edit mode for Japanese romanization has some issues.

When multiple notes are selected and the Edit > Batch Edit dialog is used, it translates the Japanese to the target language as expected. However, the romanization is merged into one note's field.

Here is the result after batch editing two cards:

Settings:

![image](https://github.com/user-attachments/assets/616da927-e8fd-4c5d-a99a-6fa73097c84a)

Card 1:
![image](https://github.com/user-attachments/assets/d6978b06-0f7f-499d-9ac6-0bf8d8ff9298)

Card 2:
![image](https://github.com/user-attachments/assets/662d0f6b-60d2-4904-a0de-fa5fb81c4248)

Translations are placed in the correct cards, but the romanization for both cards is merged into card 1.

**Comment by kelciour** [comment]
Thank you for the report and all the screenshots! It should be fixed now.
