### ISSUE TITLE
Google Translate Anki Add-on using Korean

### ISSUE THREAD

**Issue by kraemder** [kelciour/google-translate#45]
For some reason if I translate from some language INTO Korean then it bugs out when I select multiple entries.  It tries to put all the translations for every card into the target field on the first card.  It eventually fills up.  It works fine for the other languages I attempted this with (Japanese and Latin).

**Comment by kraemder** [comment]
I'm not sure if the from language matters but I'm translating from Mandarin Chinese

**Comment by kelciour** [comment]
Thank you for the report! The add-on was updated and the issue might be fixed now. If it's not, feel free to reopen it and I'll look into it some time later.
