### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by deividaspetraitis** [kelciour/google-translate#5]
Hello,

First of all thank you for great plugin it really makes learning process much easier, much appreciated!

I noticed some cases under which definitions are not added to cards.
For example following translation: https://translate.google.com/?sl=en&tl=lt&text=specifically&op=translate it wouldn't fill up definitions.

Please see attached .gif for more details how to reproduce the issue: 
![anki-google-translate](https://user-images.githubusercontent.com/5105752/113815083-4b98aa80-977b-11eb-9af5-656f59619dbe.gif)

**Comment by kelciour** [comment]
Thank you very much for the gif! It was very helpful. The field likely contains some HTML that resulted in no definitions. The add-on was updated and it should be fixed now. 

About the second issue with translations, I don't know how to do it using the old Google Translate API, but py-googletrans with new Google Translate API seems to be working and after adding it to the add-on it should be possible to get translations too. I'll try to do it either later this week or maybe next week.
