### ISSUE TITLE
Feature request: examples, translations

### ISSUE THREAD

**Issue by deividaspetraitis** [kelciour/google-translate#6]
Its quite known fact that it is much easier to memorise new information while being able to make associations to it.
I think it would be very useful feature to be able download "examples" section ( maybe with some limit? ):
![image](https://user-images.githubusercontent.com/5105752/113815945-a979c200-977c-11eb-9c93-588aeae51a39.png)

Also I've noticed that only first word of the translation is filled up ( you can see it in action in .gif attached to this issue: https://github.com/kelciour/google-translate/issues/5 ).
It might be useful to have more options:
![image](https://user-images.githubusercontent.com/5105752/113815985-c2827300-977c-11eb-85ea-57c3123b7e11.png) since first one is not always most accurate and there is more translations that fits better and depending on context they can have very different meanings.

**Comment by Sanookmakmak** [comment]
I have installed it but i could not figure out how it works. In my case nothing happens after click on the Google Translate icon. A single screenshot without any documentation is not enough. It is also hard to find the Google Translate window as you described on your plugin page. I recon that page is only for system administrators and not for speech students. Or for Anki developers and not for Anki beginners.

A better description for totally Anki noobs would be appreciate. Thank you!

Screenshot ouf your description how it should work. There's just marked an icon of Google Translate but no description of what should happen if clicking on it.

![Snipaste_2021-04-13_09-13-42](https://user-images.githubusercontent.com/24833757/114512002-e5a79980-9c38-11eb-8a8e-b96ca104470e.jpg)

**Comment by deividaspetraitis** [comment]
@kelciour any chances this to be implemented anytime soon? I would be more than happy to contribute by creating PR.

**Comment by kelciour** [comment]
@deividaspetraitis I'll be busy for the next 2-3 days and if nothing else come up, I should have some time to do it, but I'll be okay with PR too.

**Comment by kelciour** [comment]
Thanks for creating the issue! The add-on was finally updated to support alternative translations.
