### ISSUE TITLE
Word definitions for Japanese or Chinese empty or not being fetched?

### ISSUE THREAD

**Issue by ghost** [kelciour/google-translate#9]
Maybe this isn't implemented or maybe it's just so that google doesn't have the definitions for Japanese or Chinese words?
Either in english or japanese/chinese, the Definition field remains empty.
No errors displayed, it just doesn't fetch anything. Is there any alternative to get definitions that doesn't involve Migaku?

**Comment by kelciour** [comment]
If they could be found at https://translate.google.com/, it's a bug in the add-on.

Maybe Google doesn't provide definitions for Chinese on Google Translate.  But Japanese should work now. The add-on had a bug that should be fixed now. But it appears for many Japanese words Google Translate will show no definitions.

I'm only aware of Fast Word Query and Yomichan.

- https://ankiweb.net/shared/info/1807206748

- https://animecards.site/yomichansetup/
- https://foosoft.net/projects/yomichan/
- https://tatsumoto-ren.github.io/blog/tag_yomichan.html
